### ISSUE TITLE
Support css vendorPrefix

### ISSUE THREAD

**Issue by microwin7** [bernardoamorim7/javafx-css-support-vscode#1]
VSCode `"css.lint.vendorPrefix": "warning"`  Default value
This support where is invalid css parameter
![image](https://github.com/bernardoamorim7/javafx-css-support-vscode/assets/12544425/abae5e53-0bf3-48d0-a54c-11d9ef809f15)
The message says:
`Also define a default "font-size" property for compatibility css(vendorPrefix)`
However, I have to turn it off when I use JavaFX css, but it will also turn off real errors when the parameter is written incorrectly.
Example:
![image](https://github.com/bernardoamorim7/javafx-css-support-vscode/assets/12544425/3a8e5020-d146-4fe8-b9ba-d8bb1c91e649)
I would be glad if it was possible to remove the warning from -fx of real parameters and leave it on invalid ones.

**Comment by bernardoamorim7** [comment]
Hi, @microwin7,
This should be in the README file, I'll probably update it.
`"css.lint.vendorPrefix": "ignore"` is what should be used and it only turns off the warnings, not the normal CSS errors.
The screenshot you posted has no *real* errors. If you are talking about it not warning you that units aren't specified for `-fx-background-radius`, note that also happens with normal CSS, so it's not a problem with the extension or the ignoring the vendorPrefix setting. I too get this problem but I haven't found a solution yet.
I will not set it by default to `ignore` on the extension because it could cause problems with other stuff.

**Comment by microwin7** [comment]
> Hi, @microwin7,
> This should be in the README file, I'll probably update it.
> `"css.lint.vendorPrefix": "ignore"` is what should be used and it only turns off the warnings, not the normal CSS errors.
> The screenshot you posted has no _real_ errors. If you are talking about it not warning you that units aren't specified for `-fx-background-radius`, note that also happens with normal CSS, so it's not a problem with the extension or the ignoring the vendorPrefix setting. I too get this problem but I haven't found a solution yet.
> I will not set it by default to `ignore` on the extension because it could cause problems with other stuff.

On the second screen, I specifically wrote `colsor` 35 line, this naturally cannot be

**Comment by bernardoamorim7** [comment]
Hi again, @microwin7 ,
Try using this `"css.lint.unknownVendorSpecificProperties": "error"` or `"css.lint.unknownVendorSpecificProperties": "warning"` in your Workspace's `settings.json`. It worked well for me just now.
I'll update the README once again to have this information as I don't think it's right to force it on the extension.
